contentdir: "content-en"
publishdir: "public/en"
baseURL: "http://fabiolocati.net"
languageCode: "en"
title: "Fabio Alessandro Locati"
disqusShortname: "fabiolocati"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "Fabio Alessandro Locati"
  GitHubUser: "fale"
  SidebarRecentLimit: 5
  LanguageCode: "en"
  Locale: "en_US"
taxonomies:
  tag: "tags"
  category: "categories"
