contentdir: "content"
publishdir: "public"
languageCode: "en"
title: "Fabio Alessandro Locati"
disqusShortname: "fabiolocati"
theme: fale
permalinks:
  post: /blog/:year/:month/:day/:title/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "Fabio Alessandro Locati"
  GitHubUser: "fale"
  SidebarRecentLimit: 5
  LanguageCode: "en"
  Locale: "en_US"
taxonomies:
  tag: "tags"
  category: "categories"
