contentdir: "content-en"
publishdir: "public/en"
baseURL: "http://fabiolocati.net"
languageCode: "en"
locale: "en_US"
title: "Fabio Alessandro Locati"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "Fabio Alessandro Locati"
  GitHubUser: "fale"
  SidebarRecentLimit: 5
  LanguageCode: "en"
