contentdir: "content-it"
publishdir: "public/it"
baseurl: "http://fabioalocati.it"
languageCode: "it"
title: "Fabio Alessandro Locati"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Spinning the cogs in the widgets"
  AuthorName: "Fabio Alessandro Locati"
  GitHubUser: "fale"
  SidebarRecentLimit: 5
  LanguageCode: "it"
